<?php
declare(strict_types=1);
/** @var YoulagExtension $this */
?>

<div class="yl-extension-settings-container" id="yl-settings-root">

  <form class="yl-extension-settings-form" action="<?php echo _url('extension', 'configure', 'e', urlencode(string: $this->getName())); ?>" method="post" data-auto-leave-validation="1">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <h2>Youlag settings</h2>

    <section class="yl-form-section">
      <?php
      $categories = isset($_SESSION['ext_categories']) ? $_SESSION['ext_categories'] : array();
      ?>

      <h3>Appearance & behavior</h3>

      <h4 class="mb-0">
        Video mode
        <div class="yl-form-group-help">
          Select the pages and categories whose feeds will be displayed in Youlag's video interface.
        </div>
      </h4>
      <?php if (!empty($categories)): ?>
        <div class="yl-form-category-container">
          <?php $whitelist = $this->getCategoryWhitelist(); ?>
          <!-- Place checkbox outside of label to utilize the checked="checked" state for visual statemanagement via css. -->
          <input id="yl_category_all" type="checkbox" name="yl_category_whitelist[]" value="all"
            <?php echo ((empty($whitelist) || in_array(needle: 'all', haystack: $whitelist)) && !in_array(needle: 'none', haystack: $whitelist)) ? ' checked="checked"' : ''; ?>>
          <label for="yl_category_all" class="inline-block">
            All pages and categories
          </label>
          <div class="yl-form-category-subitem-container">
            <hr>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="home"
                 <?php echo in_array(needle: 'home', haystack: $whitelist) ? ' checked="checked"' : ''; ?>>
              Subscriptions
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="important"
                 <?php echo in_array(needle: 'important', haystack: $whitelist) ? ' checked="checked"' : ''; ?>>
              Important
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="watch_later"
                 <?php echo in_array(needle: 'watch_later', haystack: $whitelist) ? ' checked="checked"' : ''; ?>>
                <span class="yl-form-category__original-label">Favorites</span>
                <span class="yl-form-category__video-label">Watch later</span>
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="playlists"
                 <?php echo in_array(needle: 'playlists', haystack: $whitelist) ? ' checked="checked"' : ''; ?>>
                <span class="yl-form-category__original-label">My Labels</span>
                <span class="yl-form-category__video-label">Playlists</span>
            </label>
            <label>
              <input type="checkbox" name="yl_category_whitelist[]" value="search_results"
                 <?php echo in_array(needle: 'search_results', haystack: $whitelist) ? ' checked="checked"' : ''; ?>>
              Search results
            </label>
            <label>
            <?php foreach ($categories as $cat): ?>
              <?php $catId = (string)$cat->id(); ?>
              <label>
                <input
                  type="checkbox"
                  name="yl_category_whitelist[]"
                  value="<?php echo 'c_' . htmlspecialchars(string: $catId); ?>"
                    <?php echo in_array(needle: 'c_' . $catId, haystack: $whitelist) ? ' checked="checked"' : ''; ?>>
                <?php echo htmlspecialchars(string: (string)$cat->name()); ?>
              </label>
            <?php endforeach; ?>
          </div>
        </div>
      <?php else: ?>
        <div class="yl-form-group-help">No categories found.</div>
      <?php endif; ?>

      <h4 class="mb-0">
        Mini player
      </h4>
      <label for="yl_miniplayer_swipe_enabled" class="flex">
          <input type="checkbox" id="yl_miniplayer_swipe_enabled" name="yl_miniplayer_swipe_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_miniplayer_swipe_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Swipe down in video mode to activate mini player
          <div class="yl-form-group-help">
            Touch devices: only swipes outside the video itself are recognized.
          </div>
        </div>
      </label>

      <h4 class="mb-0">
        Video chapters

        <div class="yl-form-group-help">
          Chapters are automatically displayed for videos that provide timestamps in the video description.
        </div>
      </h4>
      <label for="yl_chapter_progress_enabled" class="flex">
          <input type="checkbox" id="yl_chapter_progress_enabled" name="yl_chapter_progress_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_chapter_progress_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Show chapter progress indicator
          <div class="yl-form-group-help">
            A faint indicator of chapter playback progress displayed below the video.
          </div>
        </div>
      </label>

      <h4 class="mb-0">
        Watch more suggestions

        <div class="yl-form-group-help">
          The "Watch more" section appears in the video modal and only suggests entries from your subscriptions.
        </div>
      </h4>
          <?php 
            $yl_related_videos = isset($this->yl_related_videos) ? $this->yl_related_videos : null;
          ?>
        <label for="yl_related_videos_watch_later" class="flex">
          <input type="radio" id="yl_related_videos_watch_later" name="yl_related_videos" value="watch_later" class="mb-auto"
            <?php echo ($yl_related_videos === null || $yl_related_videos === "watch_later") ? ' checked="checked"' : ''; ?>>
          <div class="inline-block">
            Random from 
            <span class="yl-form-category__original-label">Favorites</span>
            <span class="yl-form-category__video-label">Watch later</span>
          </div>
        </label>
        <label for="yl_related_videos_subscriptions" class="flex">
          <input type="radio" id="yl_related_videos_subscriptions" name="yl_related_videos" value="subscriptions" class="mb-auto"
            <?php echo ($yl_related_videos === 'subscriptions') ? ' checked="checked"' : ''; ?>>
          <div class="inline-block">
            Latest from Subscriptions
          </div>
        </label>
        <label for="yl_related_videos_author" class="flex">
          <input type="radio" id="yl_related_videos_author" name="yl_related_videos" value="author" class="mb-auto"
            <?php echo ($yl_related_videos === 'author') ? ' checked="checked"' : ''; ?>>
          <div class="inline-block">
            Latest from author
          </div>
        </label>
        <label for="yl_related_videos_disabled" class="flex">
          <input type="radio" id="yl_related_videos_disabled" name="yl_related_videos" value="none" class="mb-auto"
            <?php echo ($yl_related_videos === 'none') ? ' checked="checked"' : ''; ?>>
          <div class="inline-block">
            Disable
            <div class="yl-form-group-help">
              Escape the doom scrolling.
            </div>
          </div>
        </label>


      <h4 class="mb-0">
        Feed view
      </h4>
      <label for="yl_feed_view_mobile_grid_enabled" class="flex">
          <input type="checkbox" id="yl_feed_view_mobile_grid_enabled" name="yl_feed_view_mobile_grid_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_feed_view_mobile_grid_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Use grid layout on mobile
          <div class="yl-form-group-help">
            Mobile: Use a compact two-column grid layout to display more entries at once.
          </div>
        </div>
      </label>
      <label for="yl_feed_thumbnail_screencap_enabled" class="flex">
          <input type="checkbox" id="yl_feed_thumbnail_screencap_enabled" name="yl_feed_thumbnail_screencap_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_feed_thumbnail_screencap_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Replace clickbait video thumbnails with screencaps
          <div class="yl-badge yl-badge--warning pointer-events-none">Experimental</div> 
          <div class="yl-form-group-help">
            Provides a more honest preview. Uses DeArrow's community sourced thumbnails, with YouTube's low-res screencaps as fallback.
          </div>
        </div>
      </label>
      <label for="yl_watch_later_category_filter_enabled" class="flex">
          <input type="checkbox" id="yl_watch_later_category_filter_enabled" name="yl_watch_later_category_filter_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_watch_later_category_filter_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Enable category filter in the
          <span class="yl-form-category__original-label">Favorites</span>
          <span class="yl-form-category__video-label">Watch later</span>
          page
          <div class="yl-badge yl-badge--warning pointer-events-none">Experimental</div>
          <div class="yl-form-group-help">
            Ability to filter the feed entries by their category in the
            <span class="yl-form-category__original-label">Favorites</span>
            <span class="yl-form-category__video-label">Watch later</span>
            page.
          </div>
        </div>
      </label>

      <h4 class="mb-0">
        Labels
      </h4>
      <label for="yl_video_labels_enabled" class="flex">
          <input type="checkbox" id="yl_video_labels_enabled" name="yl_video_labels_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_video_labels_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Use video platform labels
          <div class="yl-form-group-help">
            Renames "Favorites → Watch later", "My Labels → Playlists".
          </div>
        </div>
      </label>
      <label for="yl_video_unread_badge_enabled" class="flex">
          <input type="checkbox" id="yl_video_unread_badge_enabled" name="yl_video_unread_badge_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_video_unread_badge_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Show "New" badge for unwatched videos
          <div class="yl-form-group-help">
            Applied to entries in video mode only.
          </div>
        </div>
      </label>

      <h4 class="mb-0">
        Sorting
      </h4>
      <label for="yl_video_sort_modified_enabled" class="flex">
          <input type="checkbox" id="yl_video_sort_modified_enabled" name="yl_video_sort_modified_enabled" value="1" class="mb-auto"
            <?php echo ($this->yl_video_sort_modified_enabled) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Sort 
          <span class="yl-form-category__original-label">"Favorite"</span><span class="yl-form-category__video-label">"Watch later"</span> 
          by recently modified
          <div class="yl-form-group-help">
            Entries will be sorted by the time they were added or read, rather than by received date.
          </div>
        </div>
      </label>


    </section>
    <section class="yl-form-section">
      <h3>Subscription</h3>

      <h4 class="mb-0">
        YouTube shorts
      </h4>
      <label for="yl_block_youtube_shorts" class="flex">
          <input type="checkbox" id="yl_block_youtube_shorts" name="yl_block_youtube_shorts" value="1" class="mb-auto"
          <?php echo (FreshRSS_Context::$user_conf->yl_block_youtube_shorts) ? ' checked="checked"' : ''; ?>>
        <div class="inline-block">
          Block incoming YouTube shorts
          <div class="yl-form-group-help">
            Existing shorts in feeds will not be affected.
          </div>
        </div>
      </label>
    </section>
    <section class="yl-form-section">

      <h3>Default video playback source</h3>

      <div class="form-group">

        <div class="group-controls">

          <div class="yl-form-group--radio">
            <div class="form-group">
              <div class="yl-form-group--radio-input-container">
                <label for="yl_playback_youtube">YouTube</label>
                <div class="yl-form-control-radio-input">
                  <input type="radio" id="yl_playback_youtube" name="yl_invidious_enabled" value="0" 
                    <?= !$this->isInvidiousEnabled() ? 'checked="checked"' : '' ?>
                  >
                  <div class="group-controls">
                    <input type="text" value="https://youtube.com" readonly>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="yl-form-group--radio">
            <div class="form-group">
              <div class="yl-form-group--radio-input-container">
                <label for="yl_playback_invidious">Invidious</label>
                <div class="yl-form-group-help">The base URL of the Invidious instance.</div>
                <div class="yl-form-control-radio-input">
                  <input type="radio" id="yl_playback_invidious" name="yl_invidious_enabled" value="1" 
                    <?= $this->isInvidiousEnabled() ? 'checked="checked"' : '' ?>
                  >
                  <div class="group-controls">
                    <input type="text" id="yl_invidious_url_1" name="yl_invidious_url_1" placeholder="https://" value="<?php echo FreshRSS_Context::$user_conf->yl_invidious_url_1; ?>">
                  </div>
                </div>
              </div>
            </div>
            
          </div>

        </div>
      </div>

    </section>

    <div class="form-group form-actions">
      <div class="group-controls">
        <button type="submit" class="btn btn-important">Submit</button>
        <button type="reset"  class="btn">Cancel</button>

        <a id="yl_check_updates" href="https://github.com/civilblur/youlag/releases" target="_blank" rel="noopener noreferrer" class="btn">Check for updates (Github)</a>
      </div>
    </div>
  </form>

</div>
